require("movsiienko.remap")
require("movsiienko.config.lazy")
require("movsiienko.colorscheme")
require("movsiienko.line_numbers")
require("movsiienko.set")
require("movsiienko.neovide")
require("movsiienko.goto_word")
